name: release

on:
  push:
    tags:
      - '\d+\.\d+\.\d+'

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            10.0.x
      - name: 'Cache: ~/.nuget/packages'
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-
      - name: Pack
        run: dotnet pack MudBlazor.ThemeManager.slnx --configuration Release --output artifacts/packages
      - name: 'Push: nuget.org'
        run: dotnet nuget push "artifacts/packages/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_KEY }} --skip-duplicate
      - name: 'Push: GitHub Packages'
        run: dotnet nuget push "artifacts/packages/*.nupkg" --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
      - name: 'Publish: packages'
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: artifacts/packages
